# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Herb v/d Dool
tagline:          'Always a work in progress'
description:      'A little about me.'
url:              http://herbdool.github.io

author:
  name:           'Herb v/d Dool'
  url:            https://github.com/herbdool

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/herbdool/herbdool.github.com

#baseurl: 

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://herb.3speedhub.com/'
  relativeLinks: 'http://herb.3speedhub.com/links.jsonp'
  media: 'media'
  ignore:
    - .editorconfig
    - .gitignore
    - CNAME
    - index.md
    - links.jsonp
    - atom.xml
    - 404.html
    - LICENSE.md
    - README.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /public
    - /assets
    - /media
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Thought"
              value: "thought"
            - name: "Project"
              value: "project"
#    _posts/static:
#      - name: "layout"
#        field:
#          element: "hidden"
#          value: "page"
#      - name: "title"
#        field:
#          element: "text"
#          label: "Title"
#          value: ""
#      - name: "permalink"
#        field:
#          element: "text"
#          label: "Permalink"
#          value: ""
