# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Herb Dool
tagline:          'A site for me'
description:      'Testing github and jekyll.'
url:              http://herbdool.github.io

author:
  name:           'Herb Dool'
  url:            https://github.com/herbdool

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/herbdool/herbdool.github.com

# Prose
prose:
  rooturl: '_posts'
#  siteurl: 'http://herbdool.github.io/'
#  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
