# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Herb Dool
tagline:          'A site for me'
description:      'Testing github and jekyll.'
url:              http://herbdool.github.io

author:
  name:           'Herb Dool'
  url:            https://github.com/herbdool

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/herbdool/herbdool.github.com

# Prose
prose:
#  rooturl: '_posts'
  siteurl: 'http://herbdool.github.io/'
  relativeLinks: 'http://herbdool.github.io/links.jsonp'
  media: 'media'
  ignore:
    - .editorconfig
    - .gitignore
    - CNAME
    - index.md
    - links.jsonp
    - atom.xml
    - 404.html
    - LICENSE.md
    - README.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /public
    - /assets
    - /media
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
#    _posts/static:
#      - name: "layout"
#        field:
#          element: "hidden"
#          value: "page"
#      - name: "title"
#        field:
#          element: "text"
#          label: "Title"
#          value: ""
#      - name: "permalink"
#        field:
#          element: "text"
#          label: "Permalink"
#          value: ""
